# Generated by Django 6.0.1 on 2026-01-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phytochemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(max_length=255)),
                ('cid', models.CharField(blank=True, max_length=100)),
                ('reference', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phytochemicals', to='core.plant')),
            ],
            options={
                'unique_together': {('plant', 'compound_name', 'cid')},
            },
        ),
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='core.plant')),
            ],
            options={
                'unique_together': {('plant', 'name')},
            },
        ),
    ]
